export const BOOKING_AVAILABLE_TIME_REQUEST = "BOOKING_AVAILABLE_TIME_REQUEST";
export const BOOKING_AVAILABLE_TIME_SUCCESS = "BOOKING_AVAILABLE_TIME_SUCCESS";
export const BOOKING_AVAILABLE_TIME_FAIL = "BOOKING_AVAILABLE_TIME_FAIL";

export const BOOKING_SAVE_REQUEST = "BOOKING_SAVE_REQUEST";
export const BOOKING_SAVE_SUCCESS = "BOOKING_SAVE_SUCCESS";
export const BOOKING_SAVE_FAIL = "BOOKING_SAVE_FAIL";
export const BOOKING_SAVE_RESET = "BOOKING_SAVE_RESET";

export const BOOKING_SERVICE_SELECTION = "BOOKING_SERVICE_SELECTION";
export const BOOKING_DATE_SELECTION = "BOOKING_DATE_SELECTION";
export const BOOKING_TIME_SELECTION = "BOOKING_TIME_SELECTION";
export const BOOKING_TIME_REMOVE = "BOOKING_TIME_REMOVE";
export const BOOKING_NAME_SELECTION = "BOOKING_NAME_SELECTION";
export const BOOKING_LASTNAME_SELECTION = "BOOKING_LASTNAME_SELECTION";

export const BOOKING_INFO_REMOVE = "BOOKING_INFO_REMOVE";

export const BOOKING_DETAILS_REQUEST = "BOOKING_DETAILS_REQUEST";
export const BOOKING_DETAILS_SUCCESS = "BOOKING_DETAILS_SUCCESS";
export const BOOKING_DETAILS_FAIL = "BOOKING_DETAILS_FAIL";

export const BOOKING_LIST_USER_REQUEST = "BOOKING_LIST_USER_REQUEST";
export const BOOKING_LIST_USER_SUCCESS = "BOOKING_LIST_USER_SUCCESS";
export const BOOKING_LIST_USER_FAIL = "BOOKING_LIST_USER_FAIL";

export const BOOKING_LIST_ADMIN_REQUEST = "BOOKING_LIST_ADMIN_REQUEST";
export const BOOKING_LIST_ADMIN_SUCCESS = "BOOKING_LIST_ADMIN_SUCCESS";
export const BOOKING_LIST_ADMIN_FAIL = "BOOKING_LIST_ADMIN_FAIL";

export const BOOKING_DELETE_REQUEST = "BOOKING_DELETE_REQUEST";
export const BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS";
export const BOOKING_DELETE_FAIL = "BOOKING_DELETE_FAIL";
export const BOOKING_DELETE_RESET = "BOOKING_DELETE_RESET";
